sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ScZX1R69sxGAwcjZJupyip41OSrXzi8EPdJf3y+8hdfbftlJwUo7CPPcn+UDYVSJvfUquTFj/RFTdpmkkaO65V1K4vv/jWsuW+D7y+I+opSGtQAMFdXGaheuUUixyZYyK9MIwPaWYuDRWP0CeHF5G7Cccczu4Tzb/0kbgdIEgb60R5nLzfR5lLOIA9NS1n+8mFNna+LpgeF5Sx74dwYW0szjLkh58Sd5RP6Q4uvL4K2PWRi9dDIkRLTlABWBYnCsFI5K3OYKltQhYQnKDM2L9wqso4mh0OFGJBeGg/c62+PDsJJo31az5grP8KIjs/YC44GVlrZ3YzDTlGSUwJNJYaBAOvdy+tUASEuivl87N1q7j9wKjfQ1uHln2jJwbv9RpF5acesslv5cRyu12jT22GDE2zcOO1prboR39dPfKwSDDP6So1wjhPyKZo6/csmynR3OpA2OscPtpkAAqZjaFKIIQ+4JjXw3oUIWwcYbeIw2dTsgRq56u9BRUWE1NFuMZ7RpELQkReSYCvz3fDvWv2r6DY+D2RDOjo280FEbxopCl2tAN40v8xEieIzCvZgCvy0j836hDPv2aN9+V/DeaQkspeZn4rS7Aw5YvFdVDjepFhAT2Q0jQnt70dyAvG4xa6DpNI/jcmJw2CiEvwx5jLD6ZldemylyzL5ZrzXAbzM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Land-of-Heart-s-Desire_5168
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy